const projects = [
      {
      name: "blog",
      spTitle: "Mi Blog",
      enTitle: "My Blog",
      date: "08/04/2021",
      image: "/../../images/projects/react-blog.png",
      spDescription: "Mi blog personal es un proyecto full stack, utilizando Reactjs y Typescript para el fronend y nodejs, express y mongodb para el backedn y base de datos",
      enDescription: "Full stack Personal blog project, using Reactjs and Typescript for frontend, and node and mongo for backend and database respertively",
      enAlt: "Project demo",
      featured: "true",
      type: "fullstack",
      technologies: 'ReactJs MongoDB NodeJs Express',
      all: 'true',
      customClass: 'full-visible',
      pageLink: "https://blog.carlamontano.tech",
      gitHub: "https://github.com/Cmmh1101/my-react-blog"
      },
      {
      name: "stats",
      spTitle: "Estadisticas",
      enTitle: "Stats",
      date: "08/04/2021",
      image: "/../../images/projects/react-blog.png",
      spDescription: "Pagina de estadisticas escolares Full stack, utilizando ReactJs, ChartJs, NodeJs, Express y MongoDb. Importe un archivo masivo de CSV a MongoDB para usar la data suministrada.",
      enDescription: "Full stack school stack project, using ReactJs, ChartJs, NodeJs, Express y MongoDb. Imported CSV file to MongoDB to utilize provided data",
      enAlt: "Project demo",
      featured: "true",
      type: "fullstack",
      technologies: 'ReactJs MongoDB NodeJs Express',
      all: 'true',
      customClass: 'full-visible',
      pageLink: "",
      gitHub: "https://github.com/Cmmh1101/school-stats"
      },
      {
      name: "hope-for-the-nations",
      spTitle: "Organizacion Pagina web",
      enTitle: "Non-Profit Website",
      date: "08/04/2021",
      image: "/../../images/projects/hope-for-the-nations@2x.png",
      spDescription: "Mi blog personal es un proyecto full stack, utilizando Reactjs y Typescript para el fronend y nodejs, express y mongodb para el backedn y base de datos",
      enDescription: "Full stack Personal blog project, using Reactjs and Typescript for frontend, and node and mongo for backend and database respertively",
      enAlt: "Project demo",
      featured: "true",
      type: "frontend",
      technologies: 'HTML CSS Reactstrap ReactJs',
      all: 'true',
      customClass: 'front-visible',
      pageLink: "https://hftn7.netlify.app",
      gitHub: "https://github.com/Cmmh1101/hope-react-types"
      },
      {
      name: "serving-in-christ",
      spTitle: "Organizacion Pagina Web",
      enTitle: "Non-Profit Website",
      date: "08/04/2021",
      image: "/../../images/projects/servinginchrist.png",
      spDescription: "Mi blog personal es un proyecto full stack, utilizando Reactjs y Typescript para el fronend y nodejs, express y mongodb para el backedn y base de datos",
      enDescription: "Full stack Personal blog project, using Reactjs and Typescript for frontend, and node and mongo for backend and database respertively",
      enAlt: "Non-profit or",
      featured: "true",
      type: "cms",
      technologies: 'HTML CSS WordPress Divi',
      all: 'true',
      customClass: 'cms-visible',
      pageLink: "https://www.servinginchrist.org/",
      gitHub: ""
      },
      {
      name: "war-game",
      spTitle: "Juego Interactivo",
      enTitle: "Interactive Game",
      date: "08/04/2021",
      image: "/../../images/projects/quadruple-war-game.png",
      spDescription: "Mi blog personal es un proyecto full stack, utilizando Reactjs y Typescript para el fronend y nodejs, express y mongodb para el backedn y base de datos",
      enDescription: "Full stack Personal blog project, using Reactjs and Typescript for frontend, and node and mongo for backend and database respertively",
      enAlt: "Project demo",
      featured: "true",
      type: "frontend",
      technologies: 'HTML CSS Reactstrap ReactJs',
      all: 'true',
      customClass: 'front-visible',
      pageLink: "https://quadruple-war-game.netlify.app",
      gitHub: "https://github.com/Cmmh1101/team-war-game"
      },
      {
      name: "language-game",
      spTitle: "Juego Interactivo de idiomas",
      enTitle: "Interactive Language Game",
      date: "08/04/2021",
      image: "/../../images/projects/spanish-english.png",
      spDescription: "Mi blog personal es un proyecto full stack, utilizando Reactjs y Typescript para el fronend y nodejs, express y mongodb para el backedn y base de datos",
      enDescription: "Full stack Personal blog project, using Reactjs and Typescript for frontend, and node and mongo for backend and database respertively",
      enAlt: "Project demo",
      featured: "true",
      type: "frontend",
      technologies: 'HTML CSS Reactstrap ReactJs',
      all: 'true',
      customClass: 'front-visible',
      pageLink: "https://the-jar-game.netlify.app",
      gitHub: "https://github.com/Cmmh1101/amanda_carla_will_aug_21"
      },
      {
      name: "law-firm",
      spTitle: "Firma de abogados",
      enTitle: "Law Firm Landing Page",
      date: "08/04/2021",
      image: "/../../images/projects/law-template.png",
      spDescription: "Mi blog personal es un proyecto full stack, utilizando Reactjs y Typescript para el fronend y nodejs, express y mongodb para el backedn y base de datos",
      enDescription: "Full stack Personal blog project, using Reactjs and Typescript for frontend, and node and mongo for backend and database respertively",
      enAlt: "Project demo",
      featured: "true",
      type: "frontend",
      technologies: 'HTML CSS Reactstrap ReactJs',
      all: 'true',
      customClass: 'front-visible',
      pageLink: "https://law-firm-template.netlify.app",
      gitHub: "https://github.com/Cmmh1101/lawyer-template"
      },
      
];

export default projects;
