const projects = [
      {
      name: "blog",
      spTitle: "Mi Blog",
      enTitle: "My Blog",
      date: "08/04/2021",
      image: "/../../images/projects/react-blog.png",
      icon: "",
      spDescription: "Mi blog personal es un proyecto full stack, utilizando Reactjs y Typescript para el fronend y nodejs, express y mongodb para el backedn y base de datos",
      enDescription: "Full stack Personal blog project, using Reactjs and Typescript for frontend, and node and mongo for backend and database respertively",
      enAlt: "Project demo",
      featured: "true",
      type: "fullstack",
      technologies: 'ReactJs MongoDB NodeJs Express',
      all: 'true',
      customClass: 'full-visible',
      pageLink: "",
      gitHub: ""
      },
      {
      name: "hope-for-the-nations",
      spTitle: "Organizacion Pagina web",
      enTitle: "Non-Profit Website",
      date: "08/04/2021",
      image: "/../../images/projects/hope-for-the-nations@2x.png",
      icon: "",
      spDescription: "Mi blog personal es un proyecto full stack, utilizando Reactjs y Typescript para el fronend y nodejs, express y mongodb para el backedn y base de datos",
      enDescription: "Full stack Personal blog project, using Reactjs and Typescript for frontend, and node and mongo for backend and database respertively",
      enAlt: "Project demo",
      featured: "true",
      type: "frontend",
      technologies: 'HTML CSS Reactstrap ReactJs',
      all: 'true',
      customClass: 'front-visible',
      pageLink: "",
      gitHub: ""
      },
      {
      name: "serving-in-christ",
      spTitle: "Organizacion Pagina Web",
      enTitle: "Non-Profit Website",
      date: "08/04/2021",
      image: "/../../images/projects/servinginchrist.png",
      icon: "",
      spDescription: "Mi blog personal es un proyecto full stack, utilizando Reactjs y Typescript para el fronend y nodejs, express y mongodb para el backedn y base de datos",
      enDescription: "Full stack Personal blog project, using Reactjs and Typescript for frontend, and node and mongo for backend and database respertively",
      enAlt: "Non-profit or",
      featured: "true",
      type: "cms",
      technologies: 'HTML CSS WordPress Divi',
      all: 'true',
      customClass: 'cms-visible',
      pageLink: "",
      gitHub: ""
      },
      {
      name: "war-game",
      spTitle: "Juego Interactivo",
      enTitle: "Interactive Game",
      date: "08/04/2021",
      image: "/../../images/projects/quadruple-war-game.png",
      icon: "",
      spDescription: "Mi blog personal es un proyecto full stack, utilizando Reactjs y Typescript para el fronend y nodejs, express y mongodb para el backedn y base de datos",
      enDescription: "Full stack Personal blog project, using Reactjs and Typescript for frontend, and node and mongo for backend and database respertively",
      enAlt: "Project demo",
      featured: "true",
      type: "frontend",
      technologies: 'HTML CSS Reactstrap ReactJs',
      all: 'true',
      customClass: 'front-visible',
      pageLink: "",
      gitHub: ""
      },
      {
      name: "language-game",
      spTitle: "Juego Interactivo de idiomas",
      enTitle: "Interactive Language Game",
      date: "08/04/2021",
      image: "/../../images/projects/spanish-english.png",
      icon: "",
      spDescription: "Mi blog personal es un proyecto full stack, utilizando Reactjs y Typescript para el fronend y nodejs, express y mongodb para el backedn y base de datos",
      enDescription: "Full stack Personal blog project, using Reactjs and Typescript for frontend, and node and mongo for backend and database respertively",
      enAlt: "Project demo",
      featured: "true",
      type: "frontend",
      technologies: 'HTML CSS Reactstrap ReactJs',
      all: 'true',
      customClass: 'front-visible',
      pageLink: "",
      gitHub: ""
      },
      {
      name: "law-firm",
      spTitle: "Firma de abogados",
      enTitle: "Law Firm Landing Page",
      date: "08/04/2021",
      image: "/../../images/projects/law-template.png",
      icon: "",
      spDescription: "Mi blog personal es un proyecto full stack, utilizando Reactjs y Typescript para el fronend y nodejs, express y mongodb para el backedn y base de datos",
      enDescription: "Full stack Personal blog project, using Reactjs and Typescript for frontend, and node and mongo for backend and database respertively",
      enAlt: "Project demo",
      featured: "true",
      type: "frontend",
      technologies: 'HTML CSS Reactstrap ReactJs',
      all: 'true',
      customClass: 'front-visible',
      pageLink: "",
      gitHub: ""
      },
      
];

export default projects;
